services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatapp-frontend:latest
    container_name: chatapp-frontend
    environment:
      - HOST=0.0.0.0
      - PORT=4200
    ports:
      - "4201:4200"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    command: sh -c "npm start -- --host 0.0.0.0 --port 4200"
    networks:
      - app-network
  
networks:
  app-network: